version: "3.6"
services:
  server-a:
    build:
      dockerfile: a.dockerfile
      context: .
    image: a-server
    ports:
      - 8081:8080
  server-b:
    build:
      dockerfile: b.dockerfile
      context: .
    image: b-server
    ports:
      - 8082:8080