apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-example
  labels:
    proj: scoulomb
spec:
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 8080